import type { Metadata } from "next";
import "./globals.css";
import { createTheme, ThemeModeScript, ThemeProvider } from "flowbite-react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const customTheme = createTheme({
  button: {
    color: {
      primary: "bg-red-500 hover:bg-red-600",
      secondary: "bg-blue-500 hover:bg-blue-600",
    },
    size: {
      lg: "px-6 py-3 text-lg",
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <ThemeProvider theme={customTheme}>
      <html suppressHydrationWarning>
        <head>
          <ThemeModeScript />
        </head>
        <body className="min-h-screen">{children}</body>
      </html>
    </ThemeProvider>
  );
}
